### ISSUE TITLE
Helper javascript_packs_with_chunks_tag 

### ISSUE THREAD

**Issue by antonypp** [nikushi/webpack_manifest#6]
If you are using new webpack 4 split chunks API, not work javascript_packs_with_chunks_tag

**Comment by nikushi** [comment]
I just made https://github.com/nikushi/webpack_manifest/pull/7, but not well tested on integration environments because I 
and my projects that work didn't split chunks API feature. If possible, do you try that branch?

**Comment by nikushi** [comment]
Close because #7 was merged to master. Reopen the issue if you still have a problem.
